In [1]:
import numpy as np
import pickle
!pip install bcolz
import bcolz

You should consider upgrading via the '/home/varunc/env/bin/python3.7 -m pip install --upgrade pip' command.


In [2]:
from tqdm.notebook import tqdm
import string

In [3]:
import torch
import urllib
import glob
import os
import numpy as np
import pandas as pd
import torch.nn as nn
import nltk
from PIL import Image
from torchvision import transforms
import torchvision
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision.datasets as datasets 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import SnowballStemmer
from nltk.corpus import wordnet

In [4]:
import os
import torch
from PIL import Image
import pandas as pd
import spacy
from torch import nn
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms import transforms
spacy_eng = spacy.load("en_core_web_sm")

In [5]:
def read_img(file):
    img_id=[]
    for img in glob.glob(file+'*.jpg'):
        temp=os.path.basename(img)
        img_id.append(temp)
        
    return img_id

In [6]:
flickr_path = '/scratch/varunc/flickr/'

In [7]:
flickr_tar = flickr_path+'Flickr-8K.tar'

In [24]:
! tar -C $flickr_path -xvf $flickr_tar

./Flickr-8K/
./Flickr-8K/Flicker8k_Dataset/
./Flickr-8K/Flicker8k_Dataset/3089107423_81a24eaf18.jpg
./Flickr-8K/Flicker8k_Dataset/2046778775_0dd7cac6ab.jpg
./Flickr-8K/Flicker8k_Dataset/493542985_c85ad29ebe.jpg
./Flickr-8K/Flicker8k_Dataset/381275595_b429fd1639.jpg
./Flickr-8K/Flicker8k_Dataset/239807547_4923efc821.jpg
./Flickr-8K/Flicker8k_Dataset/2249480913_e1695e5c28.jpg
./Flickr-8K/Flicker8k_Dataset/2330536645_2d36b516e1.jpg
./Flickr-8K/Flicker8k_Dataset/2681215810_00b0642f7b.jpg
./Flickr-8K/Flicker8k_Dataset/1384292980_4022a7520c.jpg
./Flickr-8K/Flicker8k_Dataset/2328104318_5a43ca170c.jpg
./Flickr-8K/Flicker8k_Dataset/480607352_65614ab348.jpg
./Flickr-8K/Flicker8k_Dataset/3265578645_4044a7049a.jpg
./Flickr-8K/Flicker8k_Dataset/1312954382_cf6d70d63a.jpg
./Flickr-8K/Flicker8k_Dataset/2800990525_a1f8427272.jpg
./Flickr-8K/Flicker8k_Dataset/3189293145_35dea42679.jpg
./Flickr-8K/Flicker8k_Dataset/3520922312_e58a6cfd9c.jpg
./Flickr-8K/Flicker8k_Dataset/3170802797_3c851bb475.jpg
./Flickr

./Flickr-8K/Flicker8k_Dataset/3048211972_db71d104c2.jpg
./Flickr-8K/Flicker8k_Dataset/3042488474_0d2ec81eb8.jpg
./Flickr-8K/Flicker8k_Dataset/1260816604_570fc35836.jpg
./Flickr-8K/Flicker8k_Dataset/3323528927_7b21081271.jpg
./Flickr-8K/Flicker8k_Dataset/2466495935_623b144183.jpg
./Flickr-8K/Flicker8k_Dataset/2460799229_ce45a1d940.jpg
./Flickr-8K/Flicker8k_Dataset/3116039960_54d1d68145.jpg
./Flickr-8K/Flicker8k_Dataset/1418266617_b32143275b.jpg
./Flickr-8K/Flicker8k_Dataset/3672057606_cb6393dbd9.jpg
./Flickr-8K/Flicker8k_Dataset/3239021459_a6b71bb400.jpg
./Flickr-8K/Flicker8k_Dataset/453756106_711c20471a.jpg
./Flickr-8K/Flicker8k_Dataset/1464120327_d90279ca3a.jpg
./Flickr-8K/Flicker8k_Dataset/791338571_7f38510bf7.jpg
./Flickr-8K/Flicker8k_Dataset/295258727_eaf75e0887.jpg
./Flickr-8K/Flicker8k_Dataset/380041023_0dfd712ef1.jpg
./Flickr-8K/Flicker8k_Dataset/771366843_a66304161b.jpg
./Flickr-8K/Flicker8k_Dataset/2366421102_2d60d53a0e.jpg
./Flickr-8K/Flicker8k_Dataset/2573625591_70291c894a.j

./Flickr-8K/Flicker8k_Dataset/3301854980_233cc2f896.jpg
./Flickr-8K/Flicker8k_Dataset/365759754_6cf7068c9a.jpg
./Flickr-8K/Flicker8k_Dataset/2150564996_d173a506d7.jpg
./Flickr-8K/Flicker8k_Dataset/1459250022_bf1eddad11.jpg
./Flickr-8K/Flicker8k_Dataset/3119913014_688d4997d7.jpg
./Flickr-8K/Flicker8k_Dataset/3635177305_bfbe1fc348.jpg
./Flickr-8K/Flicker8k_Dataset/300577374_bfccb0430b.jpg
./Flickr-8K/Flicker8k_Dataset/1075867198_27ca2e7efe.jpg
./Flickr-8K/Flicker8k_Dataset/3422146099_35ffc8680e.jpg
./Flickr-8K/Flicker8k_Dataset/3106026005_473a7b1c8c.jpg
./Flickr-8K/Flicker8k_Dataset/3016521240_2ef20834b6.jpg
./Flickr-8K/Flicker8k_Dataset/2226587791_66e29dd01d.jpg
./Flickr-8K/Flicker8k_Dataset/114949897_490ca7eaec.jpg
./Flickr-8K/Flicker8k_Dataset/1404832008_68e432665b.jpg
./Flickr-8K/Flicker8k_Dataset/2942311160_a154104c62.jpg
./Flickr-8K/Flicker8k_Dataset/3227499174_07feb26337.jpg
./Flickr-8K/Flicker8k_Dataset/3624327440_bef4f33f32.jpg
./Flickr-8K/Flicker8k_Dataset/2635023078_6dae04758f

./Flickr-8K/Flicker8k_Dataset/2247192427_5e106f24a9.jpg
./Flickr-8K/Flicker8k_Dataset/3487820317_3728e7569e.jpg
./Flickr-8K/Flicker8k_Dataset/244867897_d00369a779.jpg
./Flickr-8K/Flicker8k_Dataset/2040941056_7f5fd50794.jpg
./Flickr-8K/Flicker8k_Dataset/3477715432_79d82487bb.jpg
./Flickr-8K/Flicker8k_Dataset/2868575889_2c030aa8ae.jpg
./Flickr-8K/Flicker8k_Dataset/2314732154_83bc7f7314.jpg
./Flickr-8K/Flicker8k_Dataset/3317145805_071b15debb.jpg
./Flickr-8K/Flicker8k_Dataset/3042679440_010b2c596c.jpg
./Flickr-8K/Flicker8k_Dataset/3533451027_b078e4631b.jpg
./Flickr-8K/Flicker8k_Dataset/3139160252_75109e9e05.jpg
./Flickr-8K/Flicker8k_Dataset/3665169936_01ae94c9fd.jpg
./Flickr-8K/Flicker8k_Dataset/3187117682_986ffd6b67.jpg
./Flickr-8K/Flicker8k_Dataset/530888330_a18343e38d.jpg
./Flickr-8K/Flicker8k_Dataset/2637904605_fc355816fc.jpg
./Flickr-8K/Flicker8k_Dataset/3604928725_58147c87cd.jpg
./Flickr-8K/Flicker8k_Dataset/3522349685_f046f0e250.jpg
./Flickr-8K/Flicker8k_Dataset/2481598514_05a65d1f7

./Flickr-8K/Flicker8k_Dataset/2892989340_bb7e0e5548.jpg
./Flickr-8K/Flicker8k_Dataset/3516825206_5750824874.jpg
./Flickr-8K/Flicker8k_Dataset/3551003620_0b02d76f65.jpg
./Flickr-8K/Flicker8k_Dataset/2812125355_5e11a76533.jpg
./Flickr-8K/Flicker8k_Dataset/3301822808_f2ccff86f4.jpg
./Flickr-8K/Flicker8k_Dataset/2602866141_be9928408d.jpg
./Flickr-8K/Flicker8k_Dataset/3453313865_1ebff5393c.jpg
./Flickr-8K/Flicker8k_Dataset/42637986_135a9786a6.jpg
./Flickr-8K/Flicker8k_Dataset/697582336_601462e052.jpg
./Flickr-8K/Flicker8k_Dataset/616177206_0e16c33f6b.jpg
./Flickr-8K/Flicker8k_Dataset/537579448_a7f92cef58.jpg
./Flickr-8K/Flicker8k_Dataset/2441313372_6a1d59582b.jpg
./Flickr-8K/Flicker8k_Dataset/3628059004_5c3529b120.jpg
./Flickr-8K/Flicker8k_Dataset/219070971_ae43410b9e.jpg
./Flickr-8K/Flicker8k_Dataset/1876536922_8fdf8d7028.jpg
./Flickr-8K/Flicker8k_Dataset/3437107047_715c60e9c8.jpg
./Flickr-8K/Flicker8k_Dataset/3229913073_e7857a5966.jpg
./Flickr-8K/Flicker8k_Dataset/2136514643_93d8f75a77.jp

./Flickr-8K/Flicker8k_Dataset/23445819_3a458716c1.jpg
./Flickr-8K/Flicker8k_Dataset/3692892751_f6574e2700.jpg
./Flickr-8K/Flicker8k_Dataset/3593538248_dffa1a5ed4.jpg
./Flickr-8K/Flicker8k_Dataset/189721896_1ffe76d89e.jpg
./Flickr-8K/Flicker8k_Dataset/2044063458_fcc76a7636.jpg
./Flickr-8K/Flicker8k_Dataset/3613027188_1645ca1976.jpg
./Flickr-8K/Flicker8k_Dataset/3182405529_7692256746.jpg
./Flickr-8K/Flicker8k_Dataset/2364394224_c17b09e035.jpg
./Flickr-8K/Flicker8k_Dataset/3319723910_af5b5f1fae.jpg
./Flickr-8K/Flicker8k_Dataset/2695001634_127fe2f0d7.jpg
./Flickr-8K/Flicker8k_Dataset/3415228562_4efa9c9b70.jpg
./Flickr-8K/Flicker8k_Dataset/3163477256_073605e06e.jpg
./Flickr-8K/Flicker8k_Dataset/2281006675_fde04e93dd.jpg
./Flickr-8K/Flicker8k_Dataset/2029280005_a19609c81a.jpg
./Flickr-8K/Flicker8k_Dataset/2543589122_ec3e55f434.jpg
./Flickr-8K/Flicker8k_Dataset/1119015538_e8e796281e.jpg
./Flickr-8K/Flicker8k_Dataset/2070798293_6b9405e04d.jpg
./Flickr-8K/Flicker8k_Dataset/424779662_568f9606d0.

./Flickr-8K/Flicker8k_Dataset/2565237642_bdd46d7cef.jpg
./Flickr-8K/Flicker8k_Dataset/3285180819_a9712fd2bc.jpg
./Flickr-8K/Flicker8k_Dataset/3440952969_608eb5e42b.jpg
./Flickr-8K/Flicker8k_Dataset/182493240_40410254b0.jpg
./Flickr-8K/Flicker8k_Dataset/3501781809_88429e3b83.jpg
./Flickr-8K/Flicker8k_Dataset/2865703567_52de2444f2.jpg
./Flickr-8K/Flicker8k_Dataset/406901451_7eafd7568a.jpg
./Flickr-8K/Flicker8k_Dataset/2272750492_91e8f67328.jpg
./Flickr-8K/Flicker8k_Dataset/181157221_e12410ef0b.jpg
./Flickr-8K/Flicker8k_Dataset/2301867590_98c0ecb0cb.jpg
./Flickr-8K/Flicker8k_Dataset/2369248869_0266760c4a.jpg
./Flickr-8K/Flicker8k_Dataset/1432342377_3e41603f26.jpg
./Flickr-8K/Flicker8k_Dataset/531152619_6db02a7ed9.jpg
./Flickr-8K/Flicker8k_Dataset/2331510788_986809bbb4.jpg
./Flickr-8K/Flicker8k_Dataset/2644326817_8f45080b87.jpg
./Flickr-8K/Flicker8k_Dataset/911527312_f81ee36b97.jpg
./Flickr-8K/Flicker8k_Dataset/3234890865_bb3c316968.jpg
./Flickr-8K/Flicker8k_Dataset/3309042087_ee96d94b8a.j

./Flickr-8K/Flicker8k_Dataset/3229519418_040f05ced1.jpg
./Flickr-8K/Flicker8k_Dataset/3530087422_7eb2b2c289.jpg
./Flickr-8K/Flicker8k_Dataset/2590207488_ddd89037ba.jpg
./Flickr-8K/Flicker8k_Dataset/2513260012_03d33305cf.jpg
./Flickr-8K/Flicker8k_Dataset/551664516_78a5131dc4.jpg
./Flickr-8K/Flicker8k_Dataset/3712923460_1b20ebb131.jpg
./Flickr-8K/Flicker8k_Dataset/2846843520_b0e6211478.jpg
./Flickr-8K/Flicker8k_Dataset/3665549027_d7fb05d157.jpg
./Flickr-8K/Flicker8k_Dataset/468930779_8008d90e10.jpg
./Flickr-8K/Flicker8k_Dataset/2466171100_5e60cfcc11.jpg
./Flickr-8K/Flicker8k_Dataset/3690159129_93ba49ea18.jpg
./Flickr-8K/Flicker8k_Dataset/135235570_5698072cd4.jpg
./Flickr-8K/Flicker8k_Dataset/3262475923_f1f77fcd9f.jpg
./Flickr-8K/Flicker8k_Dataset/3651107058_d84d4c3c25.jpg
./Flickr-8K/Flicker8k_Dataset/2684322797_85406f571d.jpg
./Flickr-8K/Flicker8k_Dataset/3005123298_d3017d5f5d.jpg
./Flickr-8K/Flicker8k_Dataset/326028454_fb396167e6.jpg
./Flickr-8K/Flicker8k_Dataset/3728695560_00ec1ca492.

./Flickr-8K/Flicker8k_Dataset/3306951622_93b82cac21.jpg
./Flickr-8K/Flicker8k_Dataset/1308617539_54e1a3dfbe.jpg
./Flickr-8K/Flicker8k_Dataset/3320154278_c67e01b8d1.jpg
./Flickr-8K/Flicker8k_Dataset/2403544744_cba152f5c1.jpg
./Flickr-8K/Flicker8k_Dataset/2933637854_984614e18b.jpg
./Flickr-8K/Flicker8k_Dataset/109738916_236dc456ac.jpg
./Flickr-8K/Flicker8k_Dataset/2204777844_1bcf26bf84.jpg
./Flickr-8K/Flicker8k_Dataset/3295452057_0c987f895f.jpg
./Flickr-8K/Flicker8k_Dataset/3385246141_a263d1053e.jpg
./Flickr-8K/Flicker8k_Dataset/3465000218_c94e54e208.jpg
./Flickr-8K/Flicker8k_Dataset/3656225270_cdf89e3240.jpg
./Flickr-8K/Flicker8k_Dataset/317488612_70ac35493b.jpg
./Flickr-8K/Flicker8k_Dataset/2883907436_82bf4a36b8.jpg
./Flickr-8K/Flicker8k_Dataset/3347701468_bb0001b035.jpg
./Flickr-8K/Flicker8k_Dataset/262642489_f5c6b9e65b.jpg
./Flickr-8K/Flicker8k_Dataset/1472230829_803818a383.jpg
./Flickr-8K/Flicker8k_Dataset/3091916691_b1c96669c6.jpg
./Flickr-8K/Flicker8k_Dataset/3482879314_d3387e95b1

./Flickr-8K/Flicker8k_Dataset/3143155555_32b6d24f34.jpg
./Flickr-8K/Flicker8k_Dataset/3572346664_e1e6c77f11.jpg
./Flickr-8K/Flicker8k_Dataset/2580215443_4e64afe3d5.jpg
./Flickr-8K/Flicker8k_Dataset/2100816230_ff866fb352.jpg
./Flickr-8K/Flicker8k_Dataset/1490213660_9ea45550cf.jpg
./Flickr-8K/Flicker8k_Dataset/2269795781_46a296aa21.jpg
./Flickr-8K/Flicker8k_Dataset/10815824_2997e03d76.jpg
./Flickr-8K/Flicker8k_Dataset/2538423833_d1f492d1fb.jpg
./Flickr-8K/Flicker8k_Dataset/3759230208_1c2a492b12.jpg
./Flickr-8K/Flicker8k_Dataset/2066241589_b80e9f676c.jpg
./Flickr-8K/Flicker8k_Dataset/3466891862_9afde75568.jpg
./Flickr-8K/Flicker8k_Dataset/530454257_66d58b49ee.jpg
./Flickr-8K/Flicker8k_Dataset/1423126855_6cd2a3956c.jpg
./Flickr-8K/Flicker8k_Dataset/393810324_1c33760a95.jpg
./Flickr-8K/Flicker8k_Dataset/2661138991_d55aa0e5dc.jpg
./Flickr-8K/Flicker8k_Dataset/3259110412_9908c45144.jpg
./Flickr-8K/Flicker8k_Dataset/2385871317_44cde2f354.jpg
./Flickr-8K/Flicker8k_Dataset/339658315_fbb178c252.j

./Flickr-8K/Flicker8k_Dataset/3201427741_3033f5b625.jpg
./Flickr-8K/Flicker8k_Dataset/3259883609_6a1b46919e.jpg
./Flickr-8K/Flicker8k_Dataset/2766926202_4201bf2bf9.jpg
./Flickr-8K/Flicker8k_Dataset/3487261028_30791528ec.jpg
./Flickr-8K/Flicker8k_Dataset/3263497678_8bb688ca01.jpg
./Flickr-8K/Flicker8k_Dataset/3127614086_9f1d3cf73d.jpg
./Flickr-8K/Flicker8k_Dataset/3503011427_a4ee547c77.jpg
./Flickr-8K/Flicker8k_Dataset/172092461_a9a9762e13.jpg
./Flickr-8K/Flicker8k_Dataset/3691800116_6a7b315e46.jpg
./Flickr-8K/Flicker8k_Dataset/2466093839_33bbc8cbd9.jpg
./Flickr-8K/Flicker8k_Dataset/241345656_861aacefde.jpg
./Flickr-8K/Flicker8k_Dataset/3457455611_94ee93929f.jpg
./Flickr-8K/Flicker8k_Dataset/3653484549_f316590b0f.jpg
./Flickr-8K/Flicker8k_Dataset/3289893683_d4cc3ce208.jpg
./Flickr-8K/Flicker8k_Dataset/1443807993_aebfb2784a.jpg
./Flickr-8K/Flicker8k_Dataset/541063517_35044c554a.jpg
./Flickr-8K/Flicker8k_Dataset/3273163189_dece7babf4.jpg
./Flickr-8K/Flicker8k_Dataset/3009644534_992e9ea2a7

./Flickr-8K/Flicker8k_Dataset/3067971348_69af5bb309.jpg
./Flickr-8K/Flicker8k_Dataset/3174228611_6cf9d2266b.jpg
./Flickr-8K/Flicker8k_Dataset/488416045_1c6d903fe0.jpg
./Flickr-8K/Flicker8k_Dataset/241347150_5ff37818c2.jpg
./Flickr-8K/Flicker8k_Dataset/3656104088_a0d1642fa9.jpg
./Flickr-8K/Flicker8k_Dataset/2249865945_f432c8e5da.jpg
./Flickr-8K/Flicker8k_Dataset/3155390408_8e1a81efb2.jpg
./Flickr-8K/Flicker8k_Dataset/3517023411_a8fbd15230.jpg
./Flickr-8K/Flicker8k_Dataset/396360611_941e5849a3.jpg
./Flickr-8K/Flicker8k_Dataset/3556485995_9cd40269e9.jpg
./Flickr-8K/Flicker8k_Dataset/3355827928_c96c0c3e88.jpg
./Flickr-8K/Flicker8k_Dataset/2977379863_2e8d7a104e.jpg
./Flickr-8K/Flicker8k_Dataset/2735158990_56ff6bf9b0.jpg
./Flickr-8K/Flicker8k_Dataset/542648687_adf13c406b.jpg
./Flickr-8K/Flicker8k_Dataset/2715289538_d77c8d0a85.jpg
./Flickr-8K/Flicker8k_Dataset/2831578193_3c997ae330.jpg
./Flickr-8K/Flicker8k_Dataset/3502459991_fdec2da131.jpg
./Flickr-8K/Flicker8k_Dataset/1368338041_6b4077ca98.

./Flickr-8K/Flicker8k_Dataset/2053006423_6adf69ca67.jpg
./Flickr-8K/Flicker8k_Dataset/2512683710_991c9d466d.jpg
./Flickr-8K/Flicker8k_Dataset/224702241_05af393148.jpg
./Flickr-8K/Flicker8k_Dataset/3443460885_46115463b4.jpg
./Flickr-8K/Flicker8k_Dataset/760138567_762d9022d4.jpg
./Flickr-8K/Flicker8k_Dataset/3708748633_e7e3cf4e84.jpg
./Flickr-8K/Flicker8k_Dataset/3510219078_670b6b3157.jpg
./Flickr-8K/Flicker8k_Dataset/2268596214_ca532f5c63.jpg
./Flickr-8K/Flicker8k_Dataset/2246717855_c0c08fe5d2.jpg
./Flickr-8K/Flicker8k_Dataset/3098336319_a7e5b061d0.jpg
./Flickr-8K/Flicker8k_Dataset/654130822_4aeb1f1273.jpg
./Flickr-8K/Flicker8k_Dataset/3684562647_28dc325522.jpg
./Flickr-8K/Flicker8k_Dataset/2463067409_78188c584c.jpg
./Flickr-8K/Flicker8k_Dataset/3290105461_7590f23371.jpg
./Flickr-8K/Flicker8k_Dataset/373219198_149af371d9.jpg
./Flickr-8K/Flicker8k_Dataset/3297272270_285b8878b2.jpg
./Flickr-8K/Flicker8k_Dataset/1449370354_380c4123c9.jpg
./Flickr-8K/Flicker8k_Dataset/2067362863_59577f9d4d.

./Flickr-8K/Flicker8k_Dataset/1394599090_fe0ba238f0.jpg
./Flickr-8K/Flicker8k_Dataset/2084217208_7bd9bc85e5.jpg
./Flickr-8K/Flicker8k_Dataset/275516348_cbccebc125.jpg
./Flickr-8K/Flicker8k_Dataset/3326249355_e7a7c71f06.jpg
./Flickr-8K/Flicker8k_Dataset/260828892_7925d27865.jpg
./Flickr-8K/Flicker8k_Dataset/2773682293_3b712e47ff.jpg
./Flickr-8K/Flicker8k_Dataset/2632381125_de32bdfdf6.jpg
./Flickr-8K/Flicker8k_Dataset/3482859574_3908de3427.jpg
./Flickr-8K/Flicker8k_Dataset/2970183443_accd597e0a.jpg
./Flickr-8K/Flicker8k_Dataset/241345721_3f3724a7fc.jpg
./Flickr-8K/Flicker8k_Dataset/2947452329_08f2d2a467.jpg
./Flickr-8K/Flicker8k_Dataset/2675397335_1dcdbd12f5.jpg
./Flickr-8K/Flicker8k_Dataset/2895966469_53e0b29295.jpg
./Flickr-8K/Flicker8k_Dataset/2298097636_c5de0079de.jpg
./Flickr-8K/Flicker8k_Dataset/2508313118_524e93d48c.jpg
./Flickr-8K/Flicker8k_Dataset/408573233_1fff966798.jpg
./Flickr-8K/Flicker8k_Dataset/3571193625_835da90c5e.jpg
./Flickr-8K/Flicker8k_Dataset/1429814475_0b592b9995.

./Flickr-8K/Flicker8k_Dataset/210625425_fb1ef5d23b.jpg
./Flickr-8K/Flicker8k_Dataset/2676184321_858eff416b.jpg
./Flickr-8K/Flicker8k_Dataset/3220151692_d398ef9779.jpg
./Flickr-8K/Flicker8k_Dataset/3585598356_8ce815bbb9.jpg
./Flickr-8K/Flicker8k_Dataset/3364861247_d590fa170d.jpg
./Flickr-8K/Flicker8k_Dataset/2531837969_6f28637811.jpg
./Flickr-8K/Flicker8k_Dataset/2706766641_a9df81969d.jpg
./Flickr-8K/Flicker8k_Dataset/2056041678_d6b5b39b26.jpg
./Flickr-8K/Flicker8k_Dataset/3589368949_0866846949.jpg
./Flickr-8K/Flicker8k_Dataset/2187720319_112d00f07d.jpg
./Flickr-8K/Flicker8k_Dataset/2860041212_797afd6ccf.jpg
./Flickr-8K/Flicker8k_Dataset/3135826945_f7c741e5b7.jpg
./Flickr-8K/Flicker8k_Dataset/1048710776_bb5b0a5c7c.jpg
./Flickr-8K/Flicker8k_Dataset/2232518012_8cb0bbc43b.jpg
./Flickr-8K/Flicker8k_Dataset/3250589803_3f440ba781.jpg
./Flickr-8K/Flicker8k_Dataset/2287887341_663bfa15af.jpg
./Flickr-8K/Flicker8k_Dataset/2855594918_1d1e6a6061.jpg
./Flickr-8K/Flicker8k_Dataset/170100272_d820db219

./Flickr-8K/Flicker8k_Dataset/3679502342_7fe6ef8a36.jpg
./Flickr-8K/Flicker8k_Dataset/3461049169_e068ae4f25.jpg
./Flickr-8K/Flicker8k_Dataset/2471297228_b784ff61a2.jpg
./Flickr-8K/Flicker8k_Dataset/3673035152_da7ed916d9.jpg
./Flickr-8K/Flicker8k_Dataset/2205088706_d7e633e00d.jpg
./Flickr-8K/Flicker8k_Dataset/3425061393_d093edb8da.jpg
./Flickr-8K/Flicker8k_Dataset/3397310901_cbef5c06ef.jpg
./Flickr-8K/Flicker8k_Dataset/2865409854_afedf98860.jpg
./Flickr-8K/Flicker8k_Dataset/2344875609_8e172d682b.jpg
./Flickr-8K/Flicker8k_Dataset/3181322965_ce9da15271.jpg
./Flickr-8K/Flicker8k_Dataset/2828583747_8cfb7217af.jpg
./Flickr-8K/Flicker8k_Dataset/3029463004_c2d2c8f404.jpg
./Flickr-8K/Flicker8k_Dataset/3474912569_7165dc1d06.jpg
./Flickr-8K/Flicker8k_Dataset/2765747519_2b851e01d6.jpg
./Flickr-8K/Flicker8k_Dataset/3308171165_20f93d2fba.jpg
./Flickr-8K/Flicker8k_Dataset/423066487_07757b2b49.jpg
./Flickr-8K/Flicker8k_Dataset/520491467_54cbc0a866.jpg
./Flickr-8K/Flicker8k_Dataset/2860667542_95abec338

./Flickr-8K/Flicker8k_Dataset/2698666984_13e17236ae.jpg
./Flickr-8K/Flicker8k_Dataset/417577408_eb571658c1.jpg
./Flickr-8K/Flicker8k_Dataset/3405113041_4b72c24801.jpg
./Flickr-8K/Flicker8k_Dataset/656260720_a7db4ce48b.jpg
./Flickr-8K/Flicker8k_Dataset/3095137758_bdd1e613dd.jpg
./Flickr-8K/Flicker8k_Dataset/3050650135_23f9d9d2f8.jpg
./Flickr-8K/Flicker8k_Dataset/3091962081_194f2f3bd4.jpg
./Flickr-8K/Flicker8k_Dataset/1500853305_0150615ce9.jpg
./Flickr-8K/Flicker8k_Dataset/3583516290_1c87a13770.jpg
./Flickr-8K/Flicker8k_Dataset/2157003092_eaeb977789.jpg
./Flickr-8K/Flicker8k_Dataset/2352414953_10f3cd0f1f.jpg
./Flickr-8K/Flicker8k_Dataset/3289817083_4e78e1c05a.jpg
./Flickr-8K/Flicker8k_Dataset/2426215757_e008a91fcb.jpg
./Flickr-8K/Flicker8k_Dataset/3425853460_bfcd0b41f6.jpg
./Flickr-8K/Flicker8k_Dataset/3674565156_14d3b41450.jpg
./Flickr-8K/Flicker8k_Dataset/3542484764_77d8920ec9.jpg
./Flickr-8K/Flicker8k_Dataset/421153376_d1d325568f.jpg
./Flickr-8K/Flicker8k_Dataset/2657484284_daa07a3a1b

./Flickr-8K/Flicker8k_Dataset/529198549_5cd9fedf3f.jpg
./Flickr-8K/Flicker8k_Dataset/3640870001_acbd1d5ceb.jpg
./Flickr-8K/Flicker8k_Dataset/1400424834_1c76e700c4.jpg
./Flickr-8K/Flicker8k_Dataset/1663751778_90501966f0.jpg
./Flickr-8K/Flicker8k_Dataset/1714316707_8bbaa2a2ba.jpg
./Flickr-8K/Flicker8k_Dataset/2518508760_68d8df7365.jpg
./Flickr-8K/Flicker8k_Dataset/374124237_51f62b6937.jpg
./Flickr-8K/Flicker8k_Dataset/1355450069_c0675b0706.jpg
./Flickr-8K/Flicker8k_Dataset/3259225196_750c4ce0f9.jpg
./Flickr-8K/Flicker8k_Dataset/3177799416_5bd0382370.jpg
./Flickr-8K/Flicker8k_Dataset/3139876823_859c7d7c23.jpg
./Flickr-8K/Flicker8k_Dataset/3367034082_31658a89bb.jpg
./Flickr-8K/Flicker8k_Dataset/2707933554_f6dc5e0e3c.jpg
./Flickr-8K/Flicker8k_Dataset/2885912662_a3a2dfde45.jpg
./Flickr-8K/Flicker8k_Dataset/3569329986_1f468729b2.jpg
./Flickr-8K/Flicker8k_Dataset/1616016569_673de1d678.jpg
./Flickr-8K/Flicker8k_Dataset/2845691057_d4ab89d889.jpg
./Flickr-8K/Flicker8k_Dataset/408627152_1feaa4b94e

./Flickr-8K/Flicker8k_Dataset/707972553_36816e53a2.jpg
./Flickr-8K/Flicker8k_Dataset/2662890367_382eaf83bd.jpg
./Flickr-8K/Flicker8k_Dataset/2470588201_955132a946.jpg
./Flickr-8K/Flicker8k_Dataset/3271495320_bca47795fb.jpg
./Flickr-8K/Flicker8k_Dataset/3016200560_5bf8a70797.jpg
./Flickr-8K/Flicker8k_Dataset/861795382_5145ad433d.jpg
./Flickr-8K/Flicker8k_Dataset/3194134352_bc1b2a25d7.jpg
./Flickr-8K/Flicker8k_Dataset/3520936130_9e90872560.jpg
./Flickr-8K/Flicker8k_Dataset/2887744223_029f2fd5fe.jpg
./Flickr-8K/Flicker8k_Dataset/2378356400_f6bde5d9b3.jpg
./Flickr-8K/Flicker8k_Dataset/327415627_6313d32a64.jpg
./Flickr-8K/Flicker8k_Dataset/2417745327_a2c2705043.jpg
./Flickr-8K/Flicker8k_Dataset/319938879_daf0857f91.jpg
./Flickr-8K/Flicker8k_Dataset/1566117559_f5d98fbeb0.jpg
./Flickr-8K/Flicker8k_Dataset/2561295656_4f21fba209.jpg
./Flickr-8K/Flicker8k_Dataset/2188688248_f57a28a5a7.jpg
./Flickr-8K/Flicker8k_Dataset/3127629248_a955b5763b.jpg
./Flickr-8K/Flicker8k_Dataset/2630806789_6835bbae95.

./Flickr-8K/Flicker8k_Dataset/310715139_7f05468042.jpg
./Flickr-8K/Flicker8k_Dataset/190965502_0b9ed331d9.jpg
./Flickr-8K/Flicker8k_Dataset/2776029171_5abdd5a22f.jpg
./Flickr-8K/Flicker8k_Dataset/374104006_7f32c8c5de.jpg
./Flickr-8K/Flicker8k_Dataset/3439331800_e71e1d808f.jpg
./Flickr-8K/Flicker8k_Dataset/3492180255_0bd48a18f8.jpg
./Flickr-8K/Flicker8k_Dataset/1348304997_afe60a61df.jpg
./Flickr-8K/Flicker8k_Dataset/2838125339_3dd314e315.jpg
./Flickr-8K/Flicker8k_Dataset/3193511842_82549c21fb.jpg
./Flickr-8K/Flicker8k_Dataset/3429351964_531de1bf16.jpg
./Flickr-8K/Flicker8k_Dataset/1082379191_ec1e53f996.jpg
./Flickr-8K/Flicker8k_Dataset/2914800692_0c512d27b8.jpg
./Flickr-8K/Flicker8k_Dataset/3126724531_f483e1b92a.jpg
./Flickr-8K/Flicker8k_Dataset/105342180_4d4a40b47f.jpg
./Flickr-8K/Flicker8k_Dataset/536828916_b763b82949.jpg
./Flickr-8K/Flicker8k_Dataset/3518755601_cebf11e515.jpg
./Flickr-8K/Flicker8k_Dataset/2718024196_3ff660416a.jpg
./Flickr-8K/Flicker8k_Dataset/2041867793_552819a40b.j

./Flickr-8K/Flicker8k_Dataset/664341930_bd5c8b60ea.jpg
./Flickr-8K/Flicker8k_Dataset/2097398349_ff178b3f1b.jpg
./Flickr-8K/Flicker8k_Dataset/2282895743_f803f1cf01.jpg
./Flickr-8K/Flicker8k_Dataset/3580741947_cc64a83648.jpg
./Flickr-8K/Flicker8k_Dataset/2532294586_4cd76a837d.jpg
./Flickr-8K/Flicker8k_Dataset/1433397131_8634fa6664.jpg
./Flickr-8K/Flicker8k_Dataset/3109268897_d43797fc6a.jpg
./Flickr-8K/Flicker8k_Dataset/3119076670_64b5340530.jpg
./Flickr-8K/Flicker8k_Dataset/1357689954_72588dfdc4.jpg
./Flickr-8K/Flicker8k_Dataset/3341477531_4e37450f35.jpg
./Flickr-8K/Flicker8k_Dataset/3393926562_66cc01b001.jpg
./Flickr-8K/Flicker8k_Dataset/2755314937_1e974bf2b5.jpg
./Flickr-8K/Flicker8k_Dataset/3033257301_e2c8a39b04.jpg
./Flickr-8K/Flicker8k_Dataset/2105756457_a100d8434e.jpg
./Flickr-8K/Flicker8k_Dataset/439049388_3dcee2d30b.jpg
./Flickr-8K/Flicker8k_Dataset/2943384009_c8cf749181.jpg
./Flickr-8K/Flicker8k_Dataset/519228867_2fd25e38d4.jpg
./Flickr-8K/Flicker8k_Dataset/565605894_8f0bed0438.

./Flickr-8K/Flicker8k_Dataset/2358554995_54ed3baa83.jpg
./Flickr-8K/Flicker8k_Dataset/3567214106_6ece483f8b.jpg
./Flickr-8K/Flicker8k_Dataset/2363100645_c3423a0433.jpg
./Flickr-8K/Flicker8k_Dataset/3336759846_5220e27deb.jpg
./Flickr-8K/Flicker8k_Dataset/2060031241_a3ae7a06bb.jpg
./Flickr-8K/Flicker8k_Dataset/288508162_1727873924.jpg
./Flickr-8K/Flicker8k_Dataset/2892995070_39f3c9a56e.jpg
./Flickr-8K/Flicker8k_Dataset/462288558_b31a8a976f.jpg
./Flickr-8K/Flicker8k_Dataset/3457210101_3533edebc8.jpg
./Flickr-8K/Flicker8k_Dataset/2720985888_8f5920e8cf.jpg
./Flickr-8K/Flicker8k_Dataset/3337332770_5eda5cceb7.jpg
./Flickr-8K/Flicker8k_Dataset/2061144717_5b3a1864f0.jpg
./Flickr-8K/Flicker8k_Dataset/3019917636_4e0bb0acc4.jpg
./Flickr-8K/Flicker8k_Dataset/3699763582_f28c5130dd.jpg
./Flickr-8K/Flicker8k_Dataset/3171451305_f87b9e09ee.jpg
./Flickr-8K/Flicker8k_Dataset/3334537556_a2cf4e9b9a.jpg
./Flickr-8K/Flicker8k_Dataset/3512033659_7e8a0c2ffa.jpg
./Flickr-8K/Flicker8k_Dataset/2281768510_9cc5728c5

./Flickr-8K/Flicker8k_Dataset/2521878609_146143708e.jpg
./Flickr-8K/Flicker8k_Dataset/2328616978_fb21be2b87.jpg
./Flickr-8K/Flicker8k_Dataset/268365231_a0acecdc45.jpg
./Flickr-8K/Flicker8k_Dataset/350443876_c9769f5734.jpg
./Flickr-8K/Flicker8k_Dataset/3220009216_10f088185e.jpg
./Flickr-8K/Flicker8k_Dataset/2285741931_07159a21f2.jpg
./Flickr-8K/Flicker8k_Dataset/3568225554_73cdb19576.jpg
./Flickr-8K/Flicker8k_Dataset/380034515_4fbdfa6b26.jpg
./Flickr-8K/Flicker8k_Dataset/2943079526_e9033a6556.jpg
./Flickr-8K/Flicker8k_Dataset/765929807_de381cc764.jpg
./Flickr-8K/Flicker8k_Dataset/3187096035_65dc416291.jpg
./Flickr-8K/Flicker8k_Dataset/2579572274_826598b14a.jpg
./Flickr-8K/Flicker8k_Dataset/2524084967_a5e011b73d.jpg
./Flickr-8K/Flicker8k_Dataset/2890113532_ab2003d74e.jpg
./Flickr-8K/Flicker8k_Dataset/3636418958_f038130bb2.jpg
./Flickr-8K/Flicker8k_Dataset/2135502491_a15c6b5eae.jpg
./Flickr-8K/Flicker8k_Dataset/3091594712_2166604334.jpg
./Flickr-8K/Flicker8k_Dataset/534886684_a6c9f40fa1.j

./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2695085632_10c4e6ea78.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._478592803_f57cc9c461.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3376898612_41c91de476.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2689358407_9932f1b20c.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3201427741_3033f5b625.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._309238565_2d5d8dc8bf.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2893374123_087f98d58a.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2886533440_dfa832f2fa.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._1105959054_9c3a738096.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3203453897_6317aac6ff.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3185787277_b412d7f5b7.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2077079696_03380d218b.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3551170666_01df31412d.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3048211972_db71d104c2.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3203908917_53e53c03d1.j

./Flickr-8K/__MACOSX/Flicker8k_Dataset/._481732592_b50194cb89.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._190965502_0b9ed331d9.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._241347243_c751557497.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3127142756_bf0bfcb571.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._649596742_5ba84ce946.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._207584893_63e73c5c28.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3431487300_0123195f9b.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._359173181_a75c950aeb.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3320209694_db579cb607.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2223382277_9efa58ec45.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3454355269_6185e29f95.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3341084434_db5e7d1fdc.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3578068665_87bdacef6a.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2975073156_7543ed326f.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._1499581619_a5f65a882c.jpg
.

./Flickr-8K/__MACOSX/Flicker8k_Dataset/._745563422_f4fa7d9157.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3502563726_30d1ce29c8.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2045109977_b00ec93491.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._300550441_f44ec3701a.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3249891130_b241591e89.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._745966757_6d16dfad8f.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3595408539_a7d8aabc24.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3436074878_21515a6706.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._235074044_c1358888ed.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3648160673_0c783236a6.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3655155990_b0e201dd3c.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._1425013325_bff69bc9da.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2447289477_e888df561d.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3189964753_a95536ced9.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3048597471_5697538daf.jpg

./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3529211822_1dabdb3a9c.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3016178284_ec50a09e8c.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3424424006_98f9d1921c.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._1931690777_897a7d8ab6.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3474985008_0a827cd340.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._241347611_cb265be138.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._1304961697_76b86b0c18.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3171651115_e07b9d08f6.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._1303335399_b3facd47ab.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3025495499_b15797b452.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2612608861_92beaa3d0b.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2225241766_f1e7132e3e.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._299178969_5ca1de8e40.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._233242340_09963100a3.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._1464120327_d90279ca3a.jp

./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2102315758_a9148a842f.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2452686995_621878f561.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._143680966_0010ff8c60.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3268191118_ba25fabab6.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2073105823_6dacade004.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3593220756_5c416c3ceb.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3433567526_00b5a70319.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._524698457_77ba13840a.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._295433203_8185c13e08.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2863180332_372510aa49.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2545363449_1985903f82.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3614582606_16bd88dab2.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._128912885_8350d277a4.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2512682478_b67cc525c7.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._368393384_86defdcde8.jpg


./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3419238351_ac18b440c0.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3522025527_c10e6ebd26.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3568065409_1c381aa854.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3619806638_7480883039.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3423509305_e399d005db.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3131107810_7e9b96cddc.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._232193739_ed5f348c7a.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._512026551_ba63ddbd31.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2089442007_6fc798548c.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3621623690_0095e330bc.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2600867924_cd502fc911.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._261490838_2f3ac98b12.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._437404867_209625774d.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._2573141440_28a762d537.jpg
./Flickr-8K/__MACOSX/Flicker8k_Dataset/._3562302012_0cbcd01ff9.jpg

In [8]:
data_imgid=read_img(flickr_path+"Flickr-8K/Flicker8k_Dataset/")

In [9]:
data_imgid

['533713001_2d36e93509.jpg',
 '2137789511_69a6c6afa8.jpg',
 '2021613437_d99731f986.jpg',
 '288508162_1727873924.jpg',
 '3029472296_d429b1586c.jpg',
 '1460500597_866fa0c6f3.jpg',
 '2367139509_1ee4530b28.jpg',
 '2490687446_9d46fdf5a9.jpg',
 '3315726723_64c9b0a945.jpg',
 '3521201948_9049197f20.jpg',
 '772403830_08b72c7da9.jpg',
 '2623982903_58ec7c5026.jpg',
 '2856700531_312528eea4.jpg',
 '540604040_bec822c144.jpg',
 '3616525288_9c19223de6.jpg',
 '2612949583_f45b3afe33.jpg',
 '3523474077_16e14bc54c.jpg',
 '3463922449_f6040a2931.jpg',
 '3291587911_81fc33300e.jpg',
 '3474985112_24ef46e82d.jpg',
 '3264464625_c711cc40c6.jpg',
 '1308617539_54e1a3dfbe.jpg',
 '3136043366_b3f8607a0e.jpg',
 '3427614912_b147d083b2.jpg',
 '3630641436_8f9ac5b9b2.jpg',
 '1598085252_f3219b6140.jpg',
 '3334953664_a669038795.jpg',
 '241346709_23204cc2bc.jpg',
 '3143765063_a7761b16d3.jpg',
 '334737767_7f344eee16.jpg',
 '874665322_9ad05c4065.jpg',
 '2774430374_fee1d793e7.jpg',
 '3454315016_f1e30d4676.jpg',
 '3333017828_b930

In [10]:
class Vocabulary:
    def __init__(self, freq_thresh):
        self.freq_thresh = freq_thresh
        self.itos = {0:"<PAD>", 1:"<SOS>", 2:"<EOS>", 3:"<UNK>"}
        self.stoi = {"<PAD>":0, "<SOS>":1, "<EOS>":2, "<UNK>":3}
    
    def __len__(self):
        return len(self.itos)

    @staticmethod
    def tokenizer(text):
        return [tok.text.lower() for tok in spacy_eng.tokenizer(text)]

    def build_vocab(self, sentence_list):
        frequencies = {}
        idx = 4
        for sentence in sentence_list:
            for word in self.tokenizer(sentence):
                if word not in frequencies:
                    frequencies[word] = 1
                else:
                    frequencies[word] += 1
                if frequencies[word] == self.freq_thresh:
                    self.stoi[word] = idx
                    self.itos[idx] = word
                    idx += 1
    
    def numericalize(self, text):
        tok_text = self.tokenizer(text)
        vec = [self.stoi[word] if word in self.stoi else self.stoi["<UNK>"] for word in tok_text]
        return vec

In [165]:
# for test and train we need to create new text files of the format (Flickr8k.token.txt)
class FlickrDataset(Dataset):
    def __init__(self, root_dir, caption_file, lemma_file, img_file, freq_thresh, transform=None,vocab = None, lemma_vocab=None):
        self.freq_thresh = freq_thresh
        self.transform = transform
        self.root_dir = root_dir
        self.img_file = img_file
        self.caption_file = caption_file
        self.lemma_file = lemma_file
        
        self.caption_dict = self.imgId_caption_dict()
        self.lemma_dict = self.imgId_lemma_dict()
        
        self.imgs , self.captions = self.load_img_caption()
        if vocab is None:
            self.vocab = Vocabulary(self.freq_thresh)
            self.vocab.build_vocab(self.captions)
        else:
            self.vocab = vocab
            
        self.imgs_lemma , self.lemmas = self.load_img_lemma()
        if lemma_vocab is None:
            self.lemma_vocab = Vocabulary(self.freq_thresh)
            self.lemma_vocab.build_vocab(self.lemmas)
        else:
            self.lemma_vocab = lemma_vocab

    def imgId_caption_dict(self):
        caption_dict = {}
        with open(self.caption_file, 'r') as f:
            for line in f.readlines():
                line = line.strip('\n')
                temp = line.split()
                img_name, _ = temp[0].split('#')  # first word will be img_id
                description = " ".join([ word for word in temp[1:]]) # get back the description
                if img_name not in caption_dict:
                    caption_dict[img_name] = [description]
                else:
                    caption_dict[img_name].append(description)
        return caption_dict

    def imgId_lemma_dict(self):
        stop_word=list(set(stopwords.words('english')))
        lemma_dict = {}
        with open(self.lemma_file, 'r') as f:
            for line in f.readlines():
                line = line.strip('\n')
                temp = line.split()
                img_name, _ = temp[0].split('#')  # first word will be img_id
                description = " ".join([ word.lower() for word in temp[1:] if word.lower() not in stop_word]) # get back the description
                description = description.translate(str.maketrans('', '', string.punctuation)).strip()
                if img_name not in lemma_dict:
                    lemma_dict[img_name] = [description]
                else:
                    lemma_dict[img_name].append(description)
        return lemma_dict

    def load_img_caption(self):
        imgs = []
        captions = []
        with open(self.img_file, 'r') as f:
            for line in f.readlines():
                line = line.strip('\n')
                for caption in self.caption_dict[line]:
                    imgs.append(line)
                    captions.append(caption)
        return imgs, captions

    def load_img_lemma(self):
        imgs = []
        captions = []
        with open(self.img_file, 'r') as f:
            for line in f.readlines():
                line = line.strip('\n')
                for caption in self.lemma_dict[line]:
                    imgs.append(line)
                    captions.append(caption)
        return imgs, captions

    def __len__(self):
        return len(self.captions)

    def __getitem__(self, index):
        caption = self.captions[index]
        img_id = self.imgs[index]
        img = Image.open(os.path.join(self.root_dir, img_id)).convert("RGB")

        if self.transform is not None:
            img = self.transform(img)

        numericalized_caption = [self.vocab.stoi["<SOS>"]]
        numericalized_caption += self.vocab.numericalize(caption)
        numericalized_caption += [self.vocab.stoi["<EOS>"]]

        return img, torch.tensor(numericalized_caption)



In [12]:
# we can also define simply a function instead of a class
class MyCollate:
    def __init__(self, pad_idx):
        self.pad_idx = pad_idx
    
    def __call__(self, batch):
        imgs = [item[0].unsqueeze(0) for item in batch]
        imgs = torch.cat(imgs, dim=0) # batch * imgs_size * 3 (RGB)
        captions = [item[1] for item in batch] 
        captions = pad_sequence(captions, batch_first=False, padding_value=self.pad_idx)
        return imgs, captions # return the batched images and captions

In [167]:
def get_loader(root_dir, caption_file, lemma_file, img_file, transform, vocab=None, lemma_vocab=None, batch=32, num_worker=2, shuffle=True, pin_memory=True):
    dataset = FlickrDataset(root_dir=root_dir, caption_file=caption_file, lemma_file=lemma_file, img_file=img_file, freq_thresh=5, transform=transform,vocab=vocab, lemma_vocab=lemma_vocab)
    pad_idx = dataset.vocab.stoi["<PAD>"]
    loader = DataLoader(dataset=dataset,
                        batch_size=batch,
                        shuffle=shuffle,
                        collate_fn=MyCollate(pad_idx),
                        pin_memory=pin_memory,
                        num_workers=num_worker)
    return dataset,loader

In [14]:
flickr_path

'/scratch/varunc/flickr/'

In [15]:
flickr_dir = flickr_path+'Flickr/images'
img_file = flickr_path+'flickr/flickr_val_filename.txt'
caption_file = flickr_path+'flickr/flickr_val_labels.txt'

In [158]:
# Need to write a transform for images.
trans = transforms.Compose([
                            transforms.Resize((224, 224)),
                            transforms.ToTensor(),
])
dataset, dataloader = get_loader(root_dir=flickr_path+"Flickr-8K/Flicker8k_Dataset",
                        img_file=flickr_path+"Flickr-8K/Flickr_8k.trainImages.txt",
                        caption_file=flickr_path+"Flickr-8K/Flickr8k.token.txt",
                        lemma_file=flickr_path+"Flickr-8K/Flickr8k.lemma.token.txt",
                        transform=trans,
                        shuffle=False)

In [172]:
# Need to write a transform for images.
test_dataset, test_dataloader = get_loader(root_dir=flickr_path+"Flickr-8K/Flicker8k_Dataset",
                        img_file=flickr_path+"Flickr-8K/Flickr_8k.testImages.txt",
                        caption_file=flickr_path+"Flickr-8K/Flickr8k.token.txt",
                        lemma_file=flickr_path+"Flickr-8K/Flickr8k.lemma.token.txt",
                        transform=trans,
                        vocab=dataset.vocab,
                        lemma_vocab=dataset.lemma_vocab,
                        batch=32, shuffle=False)

In [17]:
dataset.lemma_dict

{'1305564994_00513f9a5b.jpg': ['man street racer armor examine tire another racer s motorbike',
  'two racer drive white bike road',
  'two motorist ride along vehicle oddly design color',
  'two person small race car drive green hill',
  'two person race uniform street car'],
 '1351764581_4d4fb1b40f.jpg': ['firefighter extinguish fire hood car',
  'fireman spray water hood small white car jack',
  'fireman spray inside open hood small white car  jack',
  'fireman use firehose car engine carjack',
  'firefighter use water extinguish car fire'],
 '1358089136_976e3d2e30.jpg': ['boy sand surf hill',
  'man attempt surf hill make sand sunny day',
  'man slide huge sand dune sunny day',
  'man surf hill sand',
  'young man short tshirt snowboard bright blue sky'],
 '1362128028_8422d53dc4.jpg': ['kid play blue tub full water outside',
  'hot day  three small kid sit big container fill water',
  'little kid sit outdoors small tub water',
  'three child squeeze plastic tub fill water play',
  

In [18]:
dataset.vocab.stoi['.']

4

In [19]:
dataset.vocab.stoi['the']

6

In [20]:
dataset.vocab.itos[9]

'snow'

In [21]:
for idx, (img, caption) in enumerate(dataloader):
    print(img.shape)
    print(caption.shape)
    if idx == 5:
        break

torch.Size([32, 3, 224, 224])
torch.Size([22, 32])
torch.Size([32, 3, 224, 224])
torch.Size([23, 32])
torch.Size([32, 3, 224, 224])
torch.Size([24, 32])
torch.Size([32, 3, 224, 224])
torch.Size([26, 32])
torch.Size([32, 3, 224, 224])
torch.Size([26, 32])
torch.Size([32, 3, 224, 224])
torch.Size([22, 32])


# GoogleNet

In [22]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [81]:
class EncoderCNN(nn.Module):
    def __init__(self):
        super(EncoderCNN, self).__init__()
        googlenet = torch.hub.load('pytorch/vision:v0.9.0', 'googlenet', pretrained=True)
        for param in googlenet.parameters():
            param.requires_grad_(False)

        modules = list(googlenet.children())[:-2]
        self.googlenet = nn.Sequential(*modules)
    def forward(self, X):
        x = self.googlenet(X)
        x = x.view(x.shape[0],-1)
        return x

In [82]:
model = EncoderCNN()
model.eval()
model.to(device)


Using cache found in /home/varunc/.cache/torch/hub/pytorch_vision_v0.9.0


EncoderCNN(
  (googlenet): Sequential(
    (0): BasicConv2d(
      (conv): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (2): BasicConv2d(
      (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    )
    (3): BasicConv2d(
      (conv): Conv2d(64, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    )
    (4): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (5): Inception(
      (branch1): BasicConv2d(
        (conv): Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, mome

In [83]:
def out_vect(filename):
    input_image = Image.open(filename)
    preprocess = trans
    input_tensor = preprocess(input_image)
    input_batch = input_tensor.unsqueeze(0) # create a mini-batch as expected by the model


    input_batch = input_batch.to(device)
    model.to(device)

    with torch.no_grad():
        output = model(input_batch)
        
    return output

In [153]:
def out_vect_tensor(input_tensor):
    input_batch = input_tensor.unsqueeze(0) # create a mini-batch as expected by the model


    input_batch = input_batch.to(device)
    model.to(device)

    with torch.no_grad():
        output = model(input_batch)
        
    return output

In [84]:
def get_vector(file,directory):
    img_vector=[]
    imgs_list = []
    with open(file,'r') as f:
        for line in f.readlines():
#             print(line.strip())
            x=out_vect(os.path.join(directory,line.strip()))
            img_vector.append(x)
            imgs_list.append(line.strip())
    return img_vector, imgs_list

In [85]:
# tensor_list = []
# pbar = tqdm(total=len(dataloader))
# for idx, (img, caption) in enumerate(dataloader):
#     with torch.no_grad():
#         img = img.to(device)
#         tensor_list.append(model(img))
#     pbar.update(1)
# pbar.refresh()

In [86]:
len(dataset.imgs)

30000

In [87]:
attr_vector, imgs_list=get_vector(flickr_path+'Flickr-8K/Flickr_8k.trainImages.txt',
                                  flickr_path+"Flickr-8K/Flicker8k_Dataset/")

In [88]:
imgs_list = np.array(imgs_list)

In [89]:
attr_tensor=torch.cat(attr_vector,0)

In [90]:
attr_tensor.shape

torch.Size([6000, 1024])

In [91]:
def knn(data,test, num = 5):
    dist = torch.norm(data - test, dim=1, p=2)
    knn = dist.topk(num, largest=False)

#     print('kNN dist: {}, index: {}'.format(knn.values, knn.indices))
    
    return knn.indices.cpu().numpy()

In [92]:
# testing
words_pref_ll = [ dataset.lemma_dict[x] for x in imgs_list[knn(attr_tensor,attr_tensor[0])]]

In [201]:
# training
def get_attr(imgId, train=True,directory=flickr_path+"Flickr-8K/Flicker8k_Dataset/"):
    vect = out_vect(os.path.join(directory,imgId))
    if train:
        words_pref_ll = [ dataset.lemma_dict[x] for x in imgs_list[knn(attr_tensor,vect,6)[1:]]]
    else:
        words_pref_ll = [ dataset.lemma_dict[x] for x in imgs_list[knn(attr_tensor,vect,5)]]
    all_words = ' '.join(reduce(lambda x,y: x+y,words_pref_ll)).split()
    top_words = [ x for x,y in Counter(all_words).most_common(5)]
    return top_words

In [178]:
with torch.no_grad():
    temp = model(imgs.to(device))

In [180]:
knn(attr_tensor,temp,6)

RuntimeError: The size of tensor a (6000) must match the size of tensor b (32) at non-singleton dimension 0

In [203]:
# training
def get_attr_tensor(img_tensor,train=True):
    model.to(device)
    img_tensor = img_tensor.to(device)
    with torch.no_grad():
        vect = model(img_tensor)
    if train:
        words_pref_ll = [ dataset.lemma_dict[x] for x in imgs_list[knn(attr_tensor,vect,6)[1:]]]
    else:
        words_pref_ll = [ dataset.lemma_dict[x] for x in imgs_list[knn(attr_tensor,vect,5)]]
    all_words = ' '.join(reduce(lambda x,y: x+y,words_pref_ll)).split()
    top_words = [ x for x,y in Counter(all_words).most_common(5)]
    return top_words

In [204]:
# training
def get_attr_encoded(vect,train=True):
    if train:
        words_pref_ll = [ dataset.lemma_dict[x] for x in imgs_list[knn(attr_tensor,vect,6)[1:]]]
    else:
        words_pref_ll = [ dataset.lemma_dict[x] for x in imgs_list[knn(attr_tensor,vect,5)]]
    all_words = ' '.join(reduce(lambda x,y: x+y,words_pref_ll)).split()
    top_words = [ x for x,y in Counter(all_words).most_common(5)]
    return top_words

In [152]:
with open(flickr_path+'Flickr-8K/Flickr_8k.testImages.txt','r') as f:
    for i in range(5):
        line = os.path.basename(f.readline().strip())
        print(get_attr(line))
        print(test_dataset.caption_dict[line])
        print()

['dog', 'brown', 'two', 'run', 'black']
['The dogs are in the snow in front of a fence .', 'The dogs play on the snow .', 'Two brown dogs playfully fight in the snow .', 'Two brown dogs wrestle in the snow .', 'Two dogs playing in the snow .']

['dog', 'pool', 'jump', 'brown', 'play']
['a brown and white dog swimming towards some in the pool', 'A dog in a swimming pool swims toward sombody we cannot see .', 'A dog swims in a pool near a person .', 'Small dog is paddling through the water in a pool .', 'The small brown and white dog is in the pool .']

['woman', 'man', 'red', 'hold', 'tent']
['A man and a woman in festive costumes dancing .', 'A man and a woman with feathers on her head dance .', 'A man and a woman wearing decorative costumes and dancing in a crowd of onlookers .', 'one performer wearing a feathered headdress dancing with another performer in the streets', 'Two people are dancing with drums on the right and a crowd behind them .']

['man', 'jump', 'girl', 'yellow', 'dre

In [200]:
for idx, (imgs,capts) in enumerate(test_dataloader):
#     line = os.path.basename(f.readline().strip())
    x = []
    for img_idx in range(imgs.shape[0]):
        x.append(test_dataset.vocab.numericalize(' '.join(get_attr_tensor(imgs[img_idx][None,:]))))
#         print(capts.shape)
#     print(x)
    print(torch.tensor(x))
    print(np.vectorize(lambda x: dataset.vocab.itos[x])(capts.cpu().numpy().squeeze()).T)
    print()
    if idx == 25:
        break

tensor([[  7,  12,  46, 285,  17],
        [  7,  12,  46, 285,  17],
        [  7,  12,  46, 285,  17],
        [  7,  12,  46, 285,  17],
        [  7,  12,  46, 285,  17],
        [  7, 164, 235,  12, 146],
        [  7, 164, 235,  12, 146],
        [  7, 164, 235,  12, 146],
        [  7, 164, 235,  12, 146],
        [  7, 164, 235,  12, 146],
        [ 36,  23,  18, 468, 644],
        [ 36,  23,  18, 468, 644],
        [ 36,  23,  18, 468, 644],
        [ 36,  23,  18, 468, 644],
        [ 36,  23,  18, 468, 644],
        [ 23, 235,  26,  86, 465],
        [ 23, 235,  26,  86, 465],
        [ 23, 235,  26,  86, 465],
        [ 23, 235,  26,  86, 465],
        [ 23, 235,  26,  86, 465],
        [232, 204,  18, 182, 712],
        [232, 204,  18, 182, 712],
        [232, 204,  18, 182, 712],
        [232, 204,  18, 182, 712],
        [232, 204,  18, 182, 712],
        [  7, 285,  12, 133,  50],
        [  7, 285,  12, 133,  50],
        [  7, 285,  12, 133,  50],
        [  7, 285,  

tensor([[  7,  61,  56, 235,  17],
        [ 23,  26, 468, 160, 413],
        [ 23,  26, 468, 160, 413],
        [ 23,  26, 468, 160, 413],
        [ 23,  26, 468, 160, 413],
        [ 23,  26, 468, 160, 413],
        [ 23, 120, 123,  36, 670],
        [ 23, 120, 123,  36, 670],
        [ 23, 120, 123,  36, 670],
        [ 23, 120, 123,  36, 670],
        [ 23, 120, 123,  36, 670],
        [ 23, 124, 100, 162,  75],
        [ 23, 124, 100, 162,  75],
        [ 23, 124, 100, 162,  75],
        [ 23, 124, 100, 162,  75],
        [ 23, 124, 100, 162,  75],
        [  7,  46,  12, 146,  17],
        [  7,  46,  12, 146,  17],
        [  7,  46,  12, 146,  17],
        [  7,  46,  12, 146,  17],
        [  7,  46,  12, 146,  17],
        [254, 468,  26, 148,  22],
        [254, 468,  26, 148,  22],
        [254, 468,  26, 148,  22],
        [254, 468,  26, 148,  22],
        [254, 468,  26, 148,  22],
        [  7,  12,  17, 285, 133],
        [  7,  12,  17, 285, 133],
        [  7,  12,  

tensor([[ 23, 124,  46,  66,  98],
        [ 23, 124,  46,  66,  98],
        [ 23,  61,  24,  36, 468],
        [ 23,  61,  24,  36, 468],
        [ 23,  61,  24,  36, 468],
        [ 23,  61,  24,  36, 468],
        [ 23,  61,  24,  36, 468],
        [  7,  61,  27,  17,  12],
        [  7,  61,  27,  17,  12],
        [  7,  61,  27,  17,  12],
        [  7,  61,  27,  17,  12],
        [  7,  61,  27,  17,  12],
        [124, 139,  23, 100, 155],
        [124, 139,  23, 100, 155],
        [124, 139,  23, 100, 155],
        [124, 139,  23, 100, 155],
        [124, 139,  23, 100, 155],
        [ 23,  36, 120,  17, 712],
        [ 23,  36, 120,  17, 712],
        [ 23,  36, 120,  17, 712],
        [ 23,  36, 120,  17, 712],
        [ 23,  36, 120,  17, 712],
        [232, 204,  18, 182,   3],
        [232, 204,  18, 182,   3],
        [232, 204,  18, 182,   3],
        [232, 204,  18, 182,   3],
        [232, 204,  18, 182,   3],
        [139, 124, 228,  23, 470],
        [139, 124, 2

tensor([[271, 204,  61,   3, 146],
        [271, 204,  61,   3, 146],
        [271, 204,  61,   3, 146],
        [ 24,  23, 285,  41,  53],
        [ 24,  23, 285,  41,  53],
        [ 24,  23, 285,  41,  53],
        [ 24,  23, 285,  41,  53],
        [ 24,  23, 285,  41,  53],
        [ 24, 254,   3,  54, 331],
        [ 24, 254,   3,  54, 331],
        [ 24, 254,   3,  54, 331],
        [ 24, 254,   3,  54, 331],
        [ 24, 254,   3,  54, 331],
        [ 23,  36,  66,  22, 767],
        [ 23,  36,  66,  22, 767],
        [ 23,  36,  66,  22, 767],
        [ 23,  36,  66,  22, 767],
        [ 23,  36,  66,  22, 767],
        [103,  24, 142, 120, 279],
        [103,  24, 142, 120, 279],
        [103,  24, 142, 120, 279],
        [103,  24, 142, 120, 279],
        [103,  24, 142, 120, 279],
        [ 23,  46, 120, 139, 530],
        [ 23,  46, 120, 139, 530],
        [ 23,  46, 120, 139, 530],
        [ 23,  46, 120, 139, 530],
        [ 23,  46, 120, 139, 530],
        [ 23,  46, 4

tensor([[271, 204,  23,  61,  54],
        [271, 204,  23,  61,  54],
        [271, 204,  23,  61,  54],
        [271, 204,  23,  61,  54],
        [658,  68,  28,  41,  39],
        [658,  68,  28,  41,  39],
        [658,  68,  28,  41,  39],
        [658,  68,  28,  41,  39],
        [658,  68,  28,  41,  39],
        [ 23,  26, 120, 658,  78],
        [ 23,  26, 120, 658,  78],
        [ 23,  26, 120, 658,  78],
        [ 23,  26, 120, 658,  78],
        [ 23,  26, 120, 658,  78],
        [103,  26,  24, 146, 696],
        [103,  26,  24, 146, 696],
        [103,  26,  24, 146, 696],
        [103,  26,  24, 146, 696],
        [103,  26,  24, 146, 696],
        [  7,  27,  12, 285, 133],
        [  7,  27,  12, 285, 133],
        [  7,  27,  12, 285, 133],
        [  7,  27,  12, 285, 133],
        [  7,  27,  12, 285, 133],
        [493,  26,  36,  41, 100],
        [493,  26,  36,  41, 100],
        [493,  26,  36,  41, 100],
        [493,  26,  36,  41, 100],
        [493,  26,  

tensor([[ 96,  23, 235, 266, 110],
        [ 96,  23, 235, 266, 110],
        [ 96,  23, 235, 266, 110],
        [ 96,  23, 235, 266, 110],
        [ 96,  23, 235, 266, 110],
        [ 36, 120,  22, 357,  41],
        [ 36, 120,  22, 357,  41],
        [ 36, 120,  22, 357,  41],
        [ 36, 120,  22, 357,  41],
        [ 36, 120,  22, 357,  41],
        [174,  23,  46, 349, 220],
        [174,  23,  46, 349, 220],
        [174,  23,  46, 349, 220],
        [174,  23,  46, 349, 220],
        [174,  23,  46, 349, 220],
        [  7,  27, 285, 133,  12],
        [  7,  27, 285, 133,  12],
        [  7,  27, 285, 133,  12],
        [  7,  27, 285, 133,  12],
        [  7,  27, 285, 133,  12],
        [ 66,  23,  26, 160,  51],
        [ 66,  23,  26, 160,  51],
        [ 66,  23,  26, 160,  51],
        [ 66,  23,  26, 160,  51],
        [ 66,  23,  26, 160,  51],
        [  7,  17,  27,  46,  61],
        [  7,  17,  27,  46,  61],
        [  7,  17,  27,  46,  61],
        [  7,  17,  

tensor([[658,  36,  23,  26,  86],
        [235,  23, 712, 357, 273],
        [235,  23, 712, 357, 273],
        [235,  23, 712, 357, 273],
        [235,  23, 712, 357, 273],
        [235,  23, 712, 357, 273],
        [ 23,  14,  36, 712, 103],
        [ 23,  14,  36, 712, 103],
        [ 23,  14,  36, 712, 103],
        [ 23,  14,  36, 712, 103],
        [ 23,  14,  36, 712, 103],
        [ 36,  66, 124,  46,  68],
        [ 36,  66, 124,  46,  68],
        [ 36,  66, 124,  46,  68],
        [ 36,  66, 124,  46,  68],
        [ 36,  66, 124,  46,  68],
        [139, 228,  23,  24, 458],
        [139, 228,  23,  24, 458],
        [139, 228,  23,  24, 458],
        [139, 228,  23,  24, 458],
        [139, 228,  23,  24, 458],
        [ 23,  24, 165, 712, 170],
        [ 23,  24, 165, 712, 170],
        [ 23,  24, 165, 712, 170],
        [ 23,  24, 165, 712, 170],
        [ 23,  24, 165, 712, 170],
        [220,  96, 123,  23, 461],
        [220,  96, 123,  23, 461],
        [220,  96, 1

tensor([[  23,  146, 2512,  103,   46],
        [  23,  146, 2512,  103,   46],
        [  24,   36,  141,   46,   26],
        [  24,   36,  141,   46,   26],
        [  24,   36,  141,   46,   26],
        [  24,   36,  141,   46,   26],
        [  24,   36,  141,   46,   26],
        [   9,    7,  160,  146,   46],
        [   9,    7,  160,  146,   46],
        [   9,    7,  160,  146,   46],
        [   9,    7,  160,  146,   46],
        [   9,    7,  160,  146,   46],
        [   7,   17,   27,   61,  285],
        [   7,   17,   27,   61,  285],
        [   7,   17,   27,   61,  285],
        [   7,   17,   27,   61,  285],
        [   7,   17,   27,   61,  285],
        [  26,   24,  146,   31,  858],
        [  26,   24,  146,   31,  858],
        [  26,   24,  146,   31,  858],
        [  26,   24,  146,   31,  858],
        [  26,   24,  146,   31,  858],
        [ 271,  204,   61,   23,  146],
        [ 271,  204,   61,   23,  146],
        [ 271,  204,   61,   23,  146],


tensor([[ 204,  271,   61,  913,  182],
        [ 204,  271,   61,  913,  182],
        [ 204,  271,   61,  913,  182],
        [  23,  124,  120,  142, 1078],
        [  23,  124,  120,  142, 1078],
        [  23,  124,  120,  142, 1078],
        [  23,  124,  120,  142, 1078],
        [  23,  124,  120,  142, 1078],
        [   7,   17,    9,  146,  285],
        [   7,   17,    9,  146,  285],
        [   7,   17,    9,  146,  285],
        [   7,   17,    9,  146,  285],
        [   7,   17,    9,  146,  285],
        [   7,   31,   46,  285,   12],
        [   7,   31,   46,  285,   12],
        [   7,   31,   46,  285,   12],
        [   7,   31,   46,  285,   12],
        [   7,   31,   46,  285,   12],
        [ 124,  100,  160,   36,   46],
        [ 124,  100,  160,   36,   46],
        [ 124,  100,  160,   36,   46],
        [ 124,  100,  160,   36,   46],
        [ 124,  100,  160,   36,   46],
        [  31,   32, 1332,   46,  174],
        [  31,   32, 1332,   46,  174],


tensor([[ 204,   62, 1141,   61,   26],
        [  23,  160,   66,   54,  867],
        [  23,  160,   66,   54,  867],
        [  23,  160,   66,   54,  867],
        [  23,  160,   66,   54,  867],
        [  23,  160,   66,   54,  867],
        [ 563,  124,  160,  273,  235],
        [ 563,  124,  160,  273,  235],
        [ 563,  124,  160,  273,  235],
        [ 563,  124,  160,  273,  235],
        [ 563,  124,  160,  273,  235],
        [ 160,   80,   23,  157,   66],
        [ 160,   80,   23,  157,   66],
        [ 160,   80,   23,  157,   66],
        [ 160,   80,   23,  157,   66],
        [ 160,   80,   23,  157,   66],
        [  26,   22,  124,  235,   31],
        [  26,   22,  124,  235,   31],
        [  26,   22,  124,  235,   31],
        [  26,   22,  124,  235,   31],
        [  26,   22,  124,  235,   31],
        [   7,   17,   27,  285,   61],
        [   7,   17,   27,  285,   61],
        [   7,   17,   27,  285,   61],
        [   7,   17,   27,  285,   61],


tensor([[   7,   17,   27,   56,  285],
        [   7,   17,   27,   56,  285],
        [  36,   46,   23,   26,  468],
        [  36,   46,   23,   26,  468],
        [  36,   46,   23,   26,  468],
        [  36,   46,   23,   26,  468],
        [  36,   46,   23,   26,  468],
        [  23,  151, 2126,  100,   24],
        [  23,  151, 2126,  100,   24],
        [  23,  151, 2126,  100,   24],
        [  23,  151, 2126,  100,   24],
        [  23,  151, 2126,  100,   24],
        [  24,  468,   23,  642,  669],
        [  24,  468,   23,  642,  669],
        [  24,  468,   23,  642,  669],
        [  24,  468,   23,  642,  669],
        [  24,  468,   23,  642,  669],
        [ 160,  124,   92,   46,   24],
        [ 160,  124,   92,   46,   24],
        [ 160,  124,   92,   46,   24],
        [ 160,  124,   92,   46,   24],
        [ 160,  124,   92,   46,   24],
        [  36,   26,  254,   23,  279],
        [  36,   26,  254,   23,  279],
        [  36,   26,  254,   23,  279],


tensor([[ 712,  101,  658,   26,   17],
        [ 712,  101,  658,   26,   17],
        [ 712,  101,  658,   26,   17],
        [   7,   17,   27,  285,   56],
        [   7,   17,   27,  285,   56],
        [   7,   17,   27,  285,   56],
        [   7,   17,   27,  285,   56],
        [   7,   17,   27,  285,   56],
        [ 226,   31, 1333,   27,  669],
        [ 226,   31, 1333,   27,  669],
        [ 226,   31, 1333,   27,  669],
        [ 226,   31, 1333,   27,  669],
        [ 226,   31, 1333,   27,  669],
        [  34,  139,  223,  320,  846],
        [  34,  139,  223,  320,  846],
        [  34,  139,  223,  320,  846],
        [  34,  139,  223,  320,  846],
        [  34,  139,  223,  320,  846],
        [  23,  712,   74,  440,   24],
        [  23,  712,   74,  440,   24],
        [  23,  712,   74,  440,   24],
        [  23,  712,   74,  440,   24],
        [  23,  712,   74,  440,   24],
        [  36,   23,  162,   26,  120],
        [  36,   23,  162,   26,  120],


tensor([[ 23, 458,  24, 712,  41],
        [ 23, 458,  24, 712,  41],
        [ 23, 458,  24, 712,  41],
        [ 23, 458,  24, 712,  41],
        [ 26,  23, 712, 120,  36],
        [ 26,  23, 712, 120,  36],
        [ 26,  23, 712, 120,  36],
        [ 26,  23, 712, 120,  36],
        [ 26,  23, 712, 120,  36],
        [ 23, 306,  36,  40,  46],
        [ 23, 306,  36,  40,  46],
        [ 23, 306,  36,  40,  46],
        [ 23, 306,  36,  40,  46],
        [ 23, 306,  36,  40,  46],
        [  7,  46,  12, 285, 133],
        [  7,  46,  12, 285, 133],
        [  7,  46,  12, 285, 133],
        [  7,  46,  12, 285, 133],
        [  7,  46,  12, 285, 133],
        [254, 146,  24, 122,  22],
        [254, 146,  24, 122,  22],
        [254, 146,  24, 122,  22],
        [254, 146,  24, 122,  22],
        [254, 146,  24, 122,  22],
        [ 23, 120,  24, 164, 226],
        [ 23, 120,  24, 164, 226],
        [ 23, 120,  24, 164, 226],
        [ 23, 120,  24, 164, 226],
        [ 23, 120,  

tensor([[124, 120,  36,  23,  46],
        [124, 120,  36,  23,  46],
        [124, 120,  36,  23,  46],
        [124, 120,  36,  23,  46],
        [124, 120,  36,  23,  46],
        [ 24,  36,  26, 658, 115],
        [ 24,  36,  26, 658, 115],
        [ 24,  36,  26, 658, 115],
        [ 24,  36,  26, 658, 115],
        [ 24,  36,  26, 658, 115],
        [ 36,  46,  14, 285,  24],
        [ 36,  46,  14, 285,  24],
        [ 36,  46,  14, 285,  24],
        [ 36,  46,  14, 285,  24],
        [ 36,  46,  14, 285,  24],
        [ 23,  36, 103, 285, 592],
        [ 23,  36, 103, 285, 592],
        [ 23,  36, 103, 285, 592],
        [ 23,  36, 103, 285, 592],
        [ 23,  36, 103, 285, 592],
        [123, 127, 396,   9, 239],
        [123, 127, 396,   9, 239],
        [123, 127, 396,   9, 239],
        [123, 127, 396,   9, 239],
        [123, 127, 396,   9, 239],
        [  7, 124, 139, 228,  31],
        [  7, 124, 139, 228,  31],
        [  7, 124, 139, 228,  31],
        [  7, 124, 1

In [94]:
dataset.caption_dict[imgs_list[0]]

['A black dog is running after a white dog in the snow .',
 'Black dog chasing brown dog through snow',
 'Two dogs chase each other across the snowy ground .',
 'Two dogs play together in the snow .',
 'Two dogs running through a low lying body of water .']

In [95]:
words_pref_ll

[['brown furry dog bite hair brown dog',
  'brown hairy dog nibble ear another dog bare teeth',
  'shaggy dog bite cheek shorthaired dog',
  'two dog bite snow',
  'two dog fight snow'],
 ['brown dog run look sky',
  'brown dog run brown grass',
  'golden colored dug prance grass',
  'brown dog play outdoors',
  'furry brown dog run grassy area'],
 ['brown dog stand beach next blue frisbee',
  'dog shake dry next blue frisbee near body water',
  'dog shake water play water frisbee',
  'brown dog shake',
  'wet dog shake water beach'],
 ['beige dog collar look brown dog swim water',
  'curly coated dog look another dog water',
  'curly haired dog stand beach stare dog deep water',
  'white  curly haired dog wear harness watch another black brown dog water',
  'wooly dog beach look toward another dog water'],
 ['black dog brown dog stand next snow',
  'little tan dog confrontation large black dog snow',
  'scruffy golden dog meeting black doberman snow',
  'two dog snow',
  'two dog stan

In [96]:
from collections import Counter

In [97]:
from functools import reduce

In [119]:
all_words = ' '.join(reduce(lambda x,y: x+y,words_pref_ll)).split()

In [122]:
top_words = [ x for x,y in Counter(all_words).most_common(5)]

In [123]:
top_words

['dog', 'brown', 'water', 'snow', 'another']

In [131]:
oh_vec_len = len(dataset.vocab.stoi)

In [132]:
top_nums = dataset.vocab.numericalize(' '.join(top_words))

In [133]:
top_nums

[7, 12, 31, 9, 74]

In [135]:
A = np.zeros(oh_vec_len)
A[top_nums] = 1
A

array([0., 0., 0., ..., 0., 0., 0.])

## Embedding layer using GLoVE

In [101]:
glove_path = '/scratch/varunc/glove/'
glove_zip = glove_path+'glove.6B.zip'

In [102]:
! unzip $glove_zip -d $glove_path

Archive:  /scratch/varunc/glove/glove.6B.zip
replace /scratch/varunc/glove/glove.6B.50d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C


In [103]:
def file_len(fname):
    with open(fname) as f:
        for i, l in enumerate(f):
            pass
    return i + 1


In [44]:
# Need not run this again and again


# words = []
# idx = 0
# word2idx = {}
# vectors = bcolz.carray(np.zeros(1), rootdir=glove_path+'6B.300.dat', mode='w')

# with open(glove_path+'glove.6B.300d.txt', 'rb') as f:
#     pbar = tqdm(total=file_len(glove_path+'glove.6B.300d.txt'))
#     for l in f:
#         line = l.decode().split()
#         word = line[0]
#         words.append(word)
#         word2idx[word] = idx
#         idx += 1
#         vect = np.array(line[1:]).astype(np.float)
#         vectors.append(vect)
#         pbar.update(1)
    
# vectors = bcolz.carray(vectors[1:].reshape((400000, 300)), rootdir=glove_path+'6B.300.dat', mode='w')
# vectors.flush()
# pickle.dump(words, open(glove_path+'6B.300_words.pkl', 'wb'))
# pickle.dump(word2idx, open(glove_path+'6B.300_idx.pkl', 'wb'))

In [118]:
vectors = bcolz.open(glove_path+'6B.300.dat')[:]
words = pickle.load(open(glove_path+'6B.300_words.pkl', 'rb'))
word2idx = pickle.load(open(glove_path+'6B.300_idx.pkl', 'rb'))

glove = {w: vectors[word2idx[w]] for w in words}

In [105]:
glove['the'].shape

(300,)

In [111]:
np.sum(glove['coal']*glove['fire'])

12.5686219647753

In [ ]:
# Get the flickr Dataset and access the vocab from it

In [54]:
target_vocab = dataset.vocab.itos

In [228]:
matrix_len = len(target_vocab)  # target vocabulary 
weights_matrix = np.zeros((matrix_len, 300))
words_found = 0

for i, word in enumerate(target_vocab):
    try: 
        weights_matrix[i] = glove[word]
        words_found += 1
    except KeyError:
        weights_matrix[i] = np.random.normal(scale=0.6, size=(300, ))
weights_matrix = torch.tensor(weights_matrix,requires_grad = False)

In [56]:
def create_emb_layer(weights_matrix, non_trainable=False):
    num_embeddings, embedding_dim = weights_matrix.size()
    emb_layer = nn.Embedding(num_embeddings, embedding_dim)
    emb_layer.load_state_dict({'weight': weights_matrix})
    if non_trainable:
        emb_layer.weight.requires_grad = False

    return emb_layer, num_embeddings

## Code for Decoder RNN

In [229]:
class DecoderRNN(nn.Module):
    """
    takes as input img vector and captions
    """
    def __init__(self):
        super().__init__()
        self.input_size = 512  # m = input_size in paper
        self.hidden_size = 512 # n = hidden_size in paper
        self.word_size = 300
        self.image_size = 1024
        self.lstm = nn.LSTMCell(self.input_size, self.hidden_size) # using single cell rather than lstm
        self.U = nn.Linear(self.word_size, self.word_size)
        self.V = nn.Linear(self.hidden_size, self.word_size)
        self.W_Y_A = nn.Linear(self.word_size, self.hidden_size)
        self.W_x_Y = nn.Linear(self.word_size, self.input_size)
        self.W_Y_h = nn.Linear(self.hidden_size, self.word_size)
        self.image_mapping = nn.Linear(self.image_size, self.input_size)
        self.diag_weight = torch.randn(self.word_size, requires_grad=True)
        self.input_diag_mat = torch.diag(self.diag_weight)

        # use the pretrained glove embedding
        self.vocab, self.num_embedding = create_emb_layer(weights_matrix, True)  # num_embeddings x 300
        self.soft = nn.Softmax(dim=1)
        self.tanh = nn.Tanh()
        self.ReLU = nn.ReLU(inplace = True)

    def input_attention(self, previous_word, attributes):
        """ 
        Apply input attention at each step.
        attributes -> matrix where columns store the word embedding, 300 x no_of_attr
        previous word -> batch x 300
        """
        # for each word in the vocabulary find the score
        score = torch.mm(self.U(previous_word), attributes) # batch x no_of_attributes
        score = self.soft(score)  # batch x no_of_attributes
        score = torch.transpose(score, 0, 1) # no_of_attributes x batch
        weighted_y = torch.mm(attributes, score)  # 300 x batch
        scaled_y = torch.mm(self.input_diag_mat, weighted_y)  # 300 x batch
        final_y = scaled_y + torch.transpose(previous_word, 0, 1) # 300 x batch
        x = self.W_x_Y(torch.transpose(final_y, 0, 1))  # batch x 512
        return x, torch.transpose(score, 0, 1)

    def output_attention(self, hidden_state, attributes):
        """
        Apply output attention at each step
        hidden_state = current hidden state of LSTMCell, used for predicting current output (batch x 512)
        attributes -> matrix where columns store the word embedding, 300 x no_of_attr
        """
        score = torch.mm(self.V(hidden_state), self.tanh(attributes)) # batch x no_of_attributes
        score = self.soft(score)  # batch x no_of_attributes
        score = torch.transpose(score, 0, 1) # no_of_attributes x batch
        weighted_y = torch.mm(self.tanh(attributes), score) # 300 x batch
        y_to_h = self.W_Y_A(torch.transpose(weighted_y, 0, 1))  # batch x 512
        hidden = hidden_state + y_to_h  # batch x 512
        hidden = self.W_Y_h(hidden)  # batch x 300
        logits = torch.mm(self.vocab, torch.transpose(hidden, 0, 1)) # no_of_attr x batch
        logits = torch.transpose(logits, 0, 1) # batch x no_of_attr
        return logits, torch.transpose(score, 0, 1)  

    def prepare_attributes(self, attr):
        no_of_attr = attr.shape[1] # batch x no_of_attr
        batch = attr.shape[0] 
        attributes = torch.zeros(batch, no_of_attr, 300)  # batch x no_of_attr x 300
        for i in range(batch):
            for j in range(no_of_attr):
                attributes[i, j, :] = self.vocab[attr[i, j]]
        return attributes

    def next_word(self, logits):
        """
        Samples from the top 3 words randomly and returns a word
        """
        probability = torch.softmax(logits, dim=1)  # batch x no_of_attr
        prob_sort, indices = torch.sort(probability, descending=True)
        # generate a array of size -> batch
        arr = torch.randint(3, (logits.shape[0],))
        random_words = torch.zeros(logits.shape[0], 300)

        for i in range(logits.shape[0]):
            ind = inidices[i, arr[i]]
            random_words[i] = self.vocab[ind]
        return random_words  # batch x 300

    def forward(self, seq_len, image_vectors, attributes, caption_ids=None):
        """
        image_vectors -> batch x img_size
        caption_ids -> batch x seq_len x word_size (make it not None, if you want to do teacher forcing)
        attributes -> batch x 5, we have 5 attributes for each of the image (contains indices of words in our dictionary)
        it should also contain <PAD>, <SOS>, <EOS> as well. 
        """
        image_vectors = self.ReLU(self.image_mapping(image_vectors)) # batch x 512
        attributes = self.prepare_attributes(attributes)
        batch_size = image_vectors.shape[0]

        Hidden_logits = torch.zeros(batch_size, seq_len, attributes.shape[1])  # batch x seq x no_of_attr
        Hidden_scores = torch.zeros(batch_size, seq_len, attributes.shape[1]) # batch x seq x no_of_attr
        Input_scores = torch.zeros(batch_size, seq_len, attributes.shape[1]) # batch x seq x no_of_attr

        hidden, cell = self.lstm(image_vectors) # batch x 512
        # Hidden_states.append(hidden.unsqueeze(1))    no need to append this first one
        logits, hidden_score = self.output_attention(hidden, attributes)
        word = self.next_word(logits)  # batch x 300

        for i in range(seq_len):
            # prepare the input using input attention
            next_input, input_score = self.input_attention(word, attributes)
            Input_scores[:, i, :] = input_score
            hidden, cell = self.lstm(next_input, (hidden, cell))
            logits, hidden_score = self.output_attention(hidden, attributes)
            Hidden_scores[:, i, :] = hidden_score
            Hidden_logits[:, i, :] = logits
            word = self.next_word(logits)  # batch x 300

        return Hidden_logits, Hidden_scores, Input_scores

In [223]:
# loss function
class MyLoss(nn.Module):
    """Crossentropy + regularization"""
    def __init__(self):
        super().__init__()
        self.criterion = nn.CrossEntropyLoss()

    def forward(self, output, target, Hidden_scores, Input_scores):
        # output -> batch x seq x no_of_attr
        # target -> batch x seq
        x = self.criterion(output, target)  # batch x seq_len
        x = x.item()
        x = torch.sum(x, dim=1)  # batch
        hidden_reg = self.regularize(Hidden_scores)
        input_reg = self.regularize(Input_scores)
        return x + hidden_reg + input_reg  # equation 10 in paper

    def regularize(self, scores):
        # batch x time x i(attr index)
        s1 = torch.sum(score, dim=1)
        s1 = s1 * s1
        s1 = torch.sqrt(torch.sum(s1, dim=1)) # sum_i_()^{0.5}

        s2 = torch.sqrt(score)
        s2 = torch.sum(s2, dim=2)
        s2 = s2 * s2
        s2 = torch.sum(s2, dim=1)  # sum_time_()^{2}
        return s1 + s2  # equation 11 in paper


## Training Loop

In [230]:
encoder = EncoderCNN()
decoder = DecoderRNN()
encoder.to(device)
decoder.to(device)

Using cache found in /home/varunc/.cache/torch/hub/pytorch_vision_v0.9.0


DecoderRNN(
  (lstm): LSTMCell(512, 512)
  (U): Linear(in_features=300, out_features=300, bias=True)
  (V): Linear(in_features=512, out_features=300, bias=True)
  (W_Y_A): Linear(in_features=300, out_features=512, bias=True)
  (W_x_Y): Linear(in_features=300, out_features=512, bias=True)
  (W_Y_h): Linear(in_features=512, out_features=300, bias=True)
  (image_mapping): Linear(in_features=1024, out_features=512, bias=True)
  (vocab): Embedding(2548, 300)
  (soft): Softmax(dim=1)
  (tanh): Tanh()
  (ReLU): ReLU(inplace=True)
)

In [214]:
list(encoder.parameters())

[Parameter containing:
 tensor([[[[ 6.2279e-02,  1.3740e-01,  2.6673e-02,  ..., -2.9114e-03,
             1.0912e-02, -1.5283e-02],
           [ 5.9184e-02,  8.4274e-02, -3.2215e-01,  ...,  1.2585e-01,
             9.3206e-02, -4.8222e-03],
           [ 3.9570e-02, -3.1750e-01, -4.6701e-01,  ...,  4.5627e-01,
             1.2769e-02, -7.3509e-03],
           ...,
           [ 4.9440e-04,  2.5545e-01,  4.6266e-01,  ..., -4.4673e-01,
            -2.1622e-02,  1.5362e-02],
           [ 4.2668e-02,  1.2893e-01, -1.0582e-01,  ..., -6.6464e-02,
             8.5844e-02,  4.9707e-02],
           [-1.2421e-03,  2.7206e-02, -6.9249e-02,  ...,  5.5079e-02,
             4.8499e-02,  8.3361e-03]],
 
          [[ 4.7645e-02,  8.3684e-02, -8.1410e-02,  ...,  3.7322e-03,
             4.0263e-02,  6.4655e-03],
           [ 1.7548e-02, -1.1273e-02, -4.3168e-01,  ...,  2.1479e-01,
             1.8248e-01,  4.4537e-02],
           [-7.0397e-02, -4.5318e-01, -4.8846e-01,  ...,  6.3857e-01,
             5.5

In [233]:
NUM_EPOCHS = 100
criterion = MyLoss()
optimizer = torch.optim.Adam(params = decoder.parameters(), lr = 0.001)

In [ ]:
for epoch in range(NUM_EPOCHS):
    for idx, (img, caption) in enumerate(dataloader):
        img = img.to(device)
        caption = caption.to(device)
        
        decoder.zero_grad()
        encoder.zero_grad()
        
        encode_out = encoder(img)
        x = []
        for out_idx in range(out.shape[0]):
            x.append(dataset.vocab.numericalize(' '.join(get_attr_encoded(encode_out[img_idx][None,:]))))
        attrs = torch.tensor(x).to(device)
        decode_out = decoder(caption.shape[0], encode_out, attrs)
        
        
        